spring:
  data:
    mongodb:
      repositories:
        type: auto
      uri: mongodb+srv://admin:t6W1tHI6iZ9YASfe@cluster0.kzzy2.mongodb.net/<dbname>?retryWrites=true&w=majority
      database: dev
