server:
  port: $PORT

spring:
  profiles:
    active: heroku
  data:
    mongodb:
      repositories:
        type: auto
      uri: mongodb+srv://admin:t6W1tHI6iZ9YASfe@cluster0.kzzy2.mongodb.net/<dbname>?retryWrites=true&w=majority&connecttimeoutms=60000
      database: dev
      auto-index-creation: false

elements:
  file:
    use-google: true
    upload-dir: /staticfiles
