server:
  port: 5000

spring:
  data:
    mongodb:
      host: 172.31.64.104
      port: 27017
      database: dev
      repositories:
        type: auto

  security:
    token-service:
      server-uri: http://localhost:5100/oauth
      client-id: elements-client
      client-secret: elements-secret
      client-id-swagger: elements-swagger
      client-secret-swagger: elements-swagger
      check-token-endpoint: ${spring.security.token-service.server-uri}/check_token

file:
  upload-dir: /uploads
