server:
  port: ${PORT:5000}

spring:
  profiles:
    active: heroku
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
  data:
    mongodb:
      repositories:
        type: auto
      uri: mongodb+srv://admin:t6W1tHI6iZ9YASfe@cluster0.kzzy2.mongodb.net/dev?retryWrites=true&w=majority&connecttimeoutms=60000
      database: dev
      auto-index-creation: false
      host: cluster0.kzzy2.mongodb.net

elements:
  file:
    use-google: true
    upload-dir: /staticfiles
