version: 0.0
os: linux
files:
  - source: /target/elements-auth-1.0-SNAPSHOT.jar
    destination: /tmp/codedeploy-deployment-staging-area/
  - source: /target/elements-api-1.0-SNAPSHOT.jar
    destination: /tmp/codedeploy-deployment-staging-area/
  - source: /target/game-session-1.0-SNAPSHOT.jar
    destination: /tmp/codedeploy-deployment-staging-area/
