version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user

hooks:
  AfterInstall:
    - location: fix_previleges.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_applications.sh
    timeout: 300
    runas: root
  ApplicationStart:
    - location: start_applications.sh
    timeout: 300
    runas: root
