version: 0.2

env:
  variables:
    s3_bucket: codepipeline-eu-north-1-393966113305/elements-back

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - gradle build -x test
  post_build:
    commands:
      - echo Moving files
      - mkdir target
      - mv elements-api/build/libs/*.jar target/elements-api.jar
      - mv elements-auth/build/libs/*.jar target/elements-auth.jar
      - mv game-session/build/libs/*.jar target/game-session.jar
      - ls
      - aws s3 cp elements-api.jar s3://$s3_bucket/elements-api.jar
      - aws s3 cp elements-auth.jar s3://$s3_bucket/elements-auth.jar
      - aws s3 cp game-session.jar s3://$s3_bucket/game-session.jar

artifacts:
  base-directory: target
  files:
    - '**/*'
  discard-paths: yes
