version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - gradle build -x test
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd

artifacts:
  files:
    elements-auth:
      files:
        - elements-auth/build/libs/*.jar
    elements-api:
      files:
        - elements-api/build/libs/*.jar
    game-session:
      files:
        - game-session/build/libs/*.jar
  discard-paths: yes
