version: 0.2

env:
  variables:
    s3_bucket: codepipeline-eu-north-1-393966113305/elements-back

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - SPRING_PROFILES_ACTIVE=aws gradle clean build -x test
  post_build:
    commands:
      - echo Moving files
      - mkdir target
      - mv elements-api/build/libs/*.jar target/elements-api.war
      - mv elements-auth/build/libs/*.jar target/elements-auth.war
      #      - mv game-session/build/libs/*.war game-session.war
      - ls
      - aws s3 rm s3://$s3_bucket/ --recursive

artifacts:
  discard-paths: yes
  files:
    - target/*.jar
    - .aws/buildspec.yml
    - .aws/scripts/*.sh

cache:
  paths:
    - /root/.m2/**/*
