version: 0.2

env:
  variables:
    s3_bucket: codepipeline-eu-north-1-393966113305

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - gradle build -x test
  post_build:
    commands:
      - echo Moving files
      - mv elements-api/build/libs/*.jar elements-api.jar
      - mv elements-auth/build/libs/*.jar elements-auth.jar
      - mv game-session/build/libs/*.jar game-session.jar
      - aws s3 sync "*.jar" s3://$s3_bucket/elements-back/target
      - ls

artifacts:
  files:
    - target/*.jar
  #    - appspec.yml
  discard-paths: yes
