version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - gradle build -x test
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd

artifacts:
  files:
    - '*/build/libs/*.jar'
  discard-paths: yes
