version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - gradle build -x test
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd

artifacts:
  files:
    elements-auth:
      base-directory: elements-auth
      files:
        - build/libs/*.jar
    elements-api:
      base-directory: elements-api
      files:
        - build/libs/*.jar
    game-session:
      base-directory: game-session
      files:
        - build/libs/*.jar
  discard-paths: yes
