#!/usr/bin/env groovy

pipeline {
    agent any

    stages {
        stage('Move docker files') {
            steps {
                sh 'ls -a'
                sh 'mv docker /var/tmp'
            }
        }
    }
}
