#!/usr/bin/env groovy

pipeline {
    agent any

    stages {
        stage('Start MongoDB') {
            steps {
                dir('docker/database/mongodb') {
                    sh 'docker-compose up'
                    sh 'docker-compose -f docker-compose.setup.yml up'
                    sh 'docker-compose -f docker-compose.post.yml up'
                }
            }
        }

        stage('Start Redis') {
            steps {
                dir('docker/database/redis') {
                    sh 'docker-compose up'
                }
            }
        }
    }
}
