version: '3.7'

services:

  mongo1:
    image: mongo-start
    build: ./mongo1
    ports:
      - 27017:27017
    volumes:
      - mongo1_db:/data
    depends_on:
      - mongo2
      - mongo3
    networks:
      - mongo

  mongo2:
    image: mongo:4.2.6-bionic
    command: --replSet rs0 --oplogSize 128
    ports:
      - 27018:27017
    volumes:
      - mongo2_db:/data
    networks:
      - mongo

  mongo3:
    image: mongo:4.2.6-bionic
    command: --replSet rs0 --oplogSize 128
    ports:
      - 27019:27017
    volumes:
      - mongo3_db:/data
    networks:
      - mongo

volumes:
  mongo1_db:
  mongo2_db:
  mongo3_db:

networks:
  mongo:
    driver: bridge
