server:
  port: 8080

datasource:
  host: localhost
  port: 27017
  user: root
  password: admin
  database: dev

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: root
      password: example
      database: dev
      authentication-database: admin

  security:
    allowed-patterns: /**

    oauth2:
      client-id: elements-client
      client-secret: elements-secret
      client-id-swagger: elements-swagger
      client-secret-swagger: elements-swagger
      grant-types: password, authorization_code, refresh_token, implicit
      refresh-token: refresh_token
      access-token-validity-seconds: 3600
      refresh-token-validity-seconds: 21600
      scope: read, write, trust
