server:
  port: 5100

spring:
  data:
    mongodb:
      host: 13.49.107.220
      port: 27017
      username: admin
      password: admin
      database: dev
      authentication-database: admin
      auto-index-creation: true
