version: '3.7'

services:

  hazelcast:
    image: hazelcast/hazelcast:3.12.1
    volumes:
      - ./resources:/configFolder
    environment:
      - JAVA_OPTS=-Dhazelcast.config=/configFolder/hazelcast.xml -Dgroup.name=test -Dgroup.password=test
    #        ports:
    #            - 5701:5701
    links:
      - "management-center:mancenter"

  management-center:
    image: hazelcast/management-center:3.12.1
    # persisting mancenter users db folder to local disk
    volumes:
      - ./mancenter3.8:/mancenter-3.8
    environment:
      - MANCENTER_DATA=/mancenter-3.8
      # enable REST interface on management center
      # http://docs.hazelcast.org/docs/latest-development/manual/html/Management/Clustered_REST_via_Management_Center.html
      - JAVA_OPTS=-Dhazelcast.mc.rest.enabled=true
    ports:
      - 8070:8080
