version: '3.7'

services:

  postgres:
    image: crunchydata/crunchy-postgres:centos7-11.2-2.3.1
    container_name: postgres
    restart: always
    env_file:
      - pgsql.list
    ports:
      - '5432:5432'
    volumes:
      - db_data:/pgdata
    networks:
      - pgnetwork

  pgadmin:
    image: crunchydata/crunchy-pgadmin4:centos7-11.2-2.3.1
    container_name: pgadmin
    depends_on:
      - postgres
    restart: always
    env_file:
      - pgadmin.list
    ports:
      - '5050:5050'
    volumes:
      - pgadmin:/pgadmin_data
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge

volumes:
  db_data:
  pgadmin: