#!/usr/bin/env groovy

pipeline {
    agent {
        docker {
            image 'openjdk:13-slim'
            args '-v /var/tmp/app:/var/lib/jenkins/workspace/elements-back/build'
        }
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                sh 'ls -a'
                sh 'chmod +x gradlew'
                sh './gradlew assemble'
                sh 'mkdir build'
                sh 'chmod -R 777 build'
                sh 'mv -v elements-api/build/libs/*.jar  /var/lib/jenkins/workspace/elements-back/build/elements-api.jar'
                sh 'mv -v game-session/build/libs/*.jar /var/lib/jenkins/workspace/elements-back/build/elements-session.jar'
            }
        }
    }
}
