version: '3.7'

services:
  arangodb:
    image: arangodb/arangodb
    container_name: arangodb
    restart: always
    env_file:
      - arangodb.list
    ports:
      - '8529:8529'
    volumes:
      - db_data:/data
      - ./entry:/docker-entrypoint-initdb.d/
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data:
