spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: root
      password: example
      database: dev
      authentication-database: admin
      repositories:
        type: auto

  session:
    store-type: hazelcast

server:
  port: 7778
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
