spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: root
      password: example
      database: dev
      authentication-database: admin
      repositories:
        type: auto

  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

server:
  port: 7778
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
logging:
  level:
    org.springframework: debug
    ee.elements: debug

elements:
  jwt:
    secret: elements-client
    expiration-ms: 86400000
